spring:
  application:
    name: auth-service
    group: com.sageDelta

# managing server properties
---
server:
  port: 8003
  servlet:
    session:
      cookie:
        name: SESSION_
      timeout: 24h

# logging
---
logging:
  level:
    root: WARN
    org:
      sageDelta:
        auth_service: INFO

# managing dataSource
---
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sage_delta}
    username: "${DB_USER:admin}"
    password: "${DB_PASSWORD:admin123}"
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: ${DB_SQL_MODE:always}
      schema-locations:
        - optional:classpath:database/schema.sql
  data:
    redis:
      host: ${DATA_REDIS_HOST:localhost}
      post: ${DATA_REDIS_PORT:6379}
      connect-timeout: 30s

  session:
    timeout: 1d
    remember-me-timeout: 30d # 30 days
    remember-me-secret: ${REMEMBER_ME_SECRET:wUJb/PEKXQDMhqnEP+B3GsDtI/cwCjyAdBxZ4TNg0/0=}



---
id-provider-ui:
  url: ${ID_PROVIDER_UI:http://localhost:3000}

---
# clients Details
clients:
  lets-split:
    client-id: ${CLIENT_ID:11001}
    redirect-urls:
      - http://localhost:3000
    client-secret: ${LETS_SPLIT_CLIENT_SECRET:g7hyJ3SDJActBtuXdb4OCN951IJUVillRrvyuSHWmV0=}
  cors:
    - http://localhost:3000
    - http://localhost:8080

# keyStore properties
key-store:
  algorithm: EC
  private-key: ${KEY_STORE_PRIVATE:MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgHUD+BshuFLbqexSylgUp0Hx149SE3s6rBZcWrugBdGShRANCAATIYzcKdAKDlPo26DQf+BslPB6CrS3S7opqhbiCCnkHazr7aVx/spL2C5/2pVDfcqiDxBfyvfSVYMZy59LAc+4p}
  public-key: ${KEY_STORE_PUBLIC:MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEyGM3CnQCg5T6Nug0H/gbJTwegq0t0u6KaoW4ggp5B2s6+2lcf7KS9guf9qVQ33Kog8QX8r30lWDGcufSwHPuKQ==}
  access-token-expiry: 30m
  refresh-token-expiry: 30d

