spring:
  application:
    name: auth-service
    group: com.sageDelta
  config:
    import:
      - optional:classpath:config/admin.yaml
      - optional:classpath:config/secret.yaml

# managing server configuration
---
server:
  port: 8003
  servlet:
    session:
      timeout: 24h

# logging
---
logging:
  level:
    root: DEBUG

# managing dataSource
---
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sage_delta}
    username: "${DB_USER:admin}"
    password: "${DB_PASSWORD:admin123}"
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: ${DB_SQL_MODE:always}
      schema-locations:
        - optional:classpath:database/schema.sql
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 300
      total-pool: 15
      max-idle: 10
      min-idle: 5