/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.25.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.sageDelta.auth_service.api;

import org.sageDelta.auth_service.model.CreateNewUserError;
import org.sageDelta.auth_service.model.CreateTokenBadRequest;
import org.sageDelta.auth_service.model.CreateTokenRequest;
import org.sageDelta.auth_service.model.CreateTokenResponse;
import org.sageDelta.auth_service.model.LogoutRequest;
import org.springframework.lang.Nullable;
import org.sageDelta.auth_service.model.RefreshTokenRequest;
import org.sageDelta.auth_service.model.RefreshTokenResponse;
import java.net.URI;
import java.util.UUID;
import org.sageDelta.auth_service.model.User;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-07-26T12:46:18.956321047Z[Etc/UTC]", comments = "Generator version: 7.25.0-SNAPSHOT")
@Validated
@Tag(name = "Clients", description = "the Clients API")
public interface ApiApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_AUTHORIZE_USER = "/api/v1/authorize";
    /**
     * GET /api/v1/authorize : authorize user
     *
     * @param redirectType  (required)
     * @param clientId  (required)
     * @param redirectUri  (required)
     * @param sessionCookie  (optional)
     * @return redirect to base url with code (status code 302)
     *         or authoriztion failed for this client (status code 400)
     */
    @Operation(
        operationId = "authorizeUser",
        summary = "authorize user",
        tags = { "Clients" },
        responses = {
            @ApiResponse(responseCode = "302", description = "redirect to base url with code"),
            @ApiResponse(responseCode = "400", description = "authoriztion failed for this client")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ApiApi.PATH_AUTHORIZE_USER
    )
    default ResponseEntity<Void> authorizeUser(
        @NotNull @Parameter(name = "redirect_type", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "redirect_type", required = true) String redirectType,
        @NotNull @Parameter(name = "client_id", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "client_id", required = true) UUID clientId,
        @NotNull @Parameter(name = "redirect_uri", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "redirect_uri", required = true) String redirectUri,
        @Parameter(name = "sessionCookie", description = "", in = ParameterIn.COOKIE) @CookieValue(name = "sessionCookie", required = false) @Nullable UUID sessionCookie
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_CREATE_NEW_USER = "/api/v1/create";
    /**
     * POST /api/v1/create : create new user
     *
     * @param host  (required)
     * @param user info regarding create User endpoint  (required)
     * @return redirect user to login page (status code 302)
     *         or user already exists or any field is missing (status code 400)
     */
    @Operation(
        operationId = "createNewUser",
        summary = "create new user",
        tags = { "Clients" },
        responses = {
            @ApiResponse(responseCode = "302", description = "redirect user to login page"),
            @ApiResponse(responseCode = "400", description = "user already exists or any field is missing", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CreateNewUserError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ApiApi.PATH_CREATE_NEW_USER,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> createNewUser(
        @NotNull @Parameter(name = "Host", description = "", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "Host", required = true) URI host,
        @Parameter(name = "User", description = "info regarding create User endpoint ", required = true) @Valid @RequestBody User user
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"BAD_REQUEST\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_EXCHANGE_TOKEN = "/api/v1/token";
    /**
     * POST /api/v1/token : exchange access_code
     * exhange access_code for accessToken and refreshToken
     *
     * @param createTokenRequest  (optional)
     * @return exchange token response (status code 200)
     *         or bad request (status code 400)
     */
    @Operation(
        operationId = "exchangeToken",
        summary = "exchange access_code",
        description = "exhange access_code for accessToken and refreshToken",
        tags = { "Clients" },
        responses = {
            @ApiResponse(responseCode = "200", description = "exchange token response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CreateTokenResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "bad request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CreateTokenBadRequest.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ApiApi.PATH_EXCHANGE_TOKEN,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<CreateTokenResponse> exchangeToken(
        @Parameter(name = "CreateTokenRequest", description = "") @Valid @RequestBody(required = false) @Nullable CreateTokenRequest createTokenRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"accessToken\" : \"abc1234\", \"refreshToken\" : \"abc2345\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"BAD_REQUEST\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GENERATE_REFRESH_TOKEN = "/api/v1/refresh";
    /**
     * POST /api/v1/refresh : generate accessToken and refreshToken
     *
     * @param refreshTokenRequest  (optional)
     * @return response to get value (status code 200)
     */
    @Operation(
        operationId = "generateRefreshToken",
        summary = "generate accessToken and refreshToken",
        tags = { "Clients" },
        responses = {
            @ApiResponse(responseCode = "200", description = "response to get value", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = RefreshTokenResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ApiApi.PATH_GENERATE_REFRESH_TOKEN,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<RefreshTokenResponse> generateRefreshToken(
        @Parameter(name = "RefreshTokenRequest", description = "") @Valid @RequestBody(required = false) @Nullable RefreshTokenRequest refreshTokenRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"refreshToken\" : \"refreshToken\", \"accessToken\" : \"accessToken\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_LOGOUT_USER = "/api/v1/logout";
    /**
     * POST /api/v1/logout
     * client logout
     *
     * @param sessionCookie  (required)
     * @param logoutRequest  (optional)
     * @return Logout user by expiring session and refreshToken (status code 204)
     */
    @Operation(
        operationId = "logoutUser",
        description = "client logout",
        tags = { "Clients" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Logout user by expiring session and refreshToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ApiApi.PATH_LOGOUT_USER,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> logoutUser(
        @NotNull @Parameter(name = "sessionCookie", description = "", required = true, in = ParameterIn.COOKIE) @CookieValue(name = "sessionCookie") String sessionCookie,
        @Parameter(name = "LogoutRequest", description = "") @Valid @RequestBody(required = false) @Nullable LogoutRequest logoutRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
