/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.25.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.sageDelta.auth_service.api;

import org.sageDelta.auth_service.model.CreateNewUserError;
import org.sageDelta.auth_service.model.CreateTokenBadRequest;
import org.sageDelta.auth_service.model.CreateTokenRequest;
import org.sageDelta.auth_service.model.CreateTokenResponse;
import org.sageDelta.auth_service.model.LoginResponse;
import org.sageDelta.auth_service.model.LoginValidationError;
import org.springframework.lang.Nullable;
import org.sageDelta.auth_service.model.RefreshTokenRequest;
import org.sageDelta.auth_service.model.RefreshTokenResponse;
import org.sageDelta.auth_service.model.User;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-08-14T09:08:03.513235097Z[Etc/UTC]", comments = "Generator version: 7.25.0-SNAPSHOT")
@Validated
@Tag(name = "client api", description = "the client api API")
public interface ApiApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_AUTHORIZE_USER = "/api/v1/oauth2/authorize";
    /**
     * GET /api/v1/oauth2/authorize : authorize user
     *
     * @param clientId  (required)
     * @param redirectUri  (required)
     * @param SESSION_  (optional)
     * @param scope  (optional)
     * @return redirect to base url with code (status code 302)
     *         or authoriztion failed for this client (status code 400)
     */
    @Operation(
        operationId = "authorizeUser",
        summary = "authorize user",
        tags = { "client api" },
        responses = {
            @ApiResponse(responseCode = "302", description = "redirect to base url with code"),
            @ApiResponse(responseCode = "400", description = "authoriztion failed for this client")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ApiApi.PATH_AUTHORIZE_USER
    )
    default ResponseEntity<Void> authorizeUser(
        @NotNull @Parameter(name = "client_id", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "client_id", required = true) String clientId,
        @NotNull @Parameter(name = "redirect_uri", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "redirect_uri", required = true) String redirectUri,
        @Parameter(name = "SESSION_", description = "", in = ParameterIn.COOKIE) @CookieValue(name = "SESSION_", required = false) @Nullable String SESSION_,
        @Parameter(name = "scope", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "scope", required = false) @Nullable String scope
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_CREATE_NEW_USER = "/api/v1/create";
    /**
     * POST /api/v1/create : create new user
     *
     * @param user info regarding create User endpoint  (required)
     * @return user created successfully (status code 200)
     *         or user already exists or any field is missing (status code 400)
     */
    @Operation(
        operationId = "createNewUser",
        summary = "create new user",
        tags = { "client api" },
        responses = {
            @ApiResponse(responseCode = "200", description = "user created successfully"),
            @ApiResponse(responseCode = "400", description = "user already exists or any field is missing", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CreateNewUserError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ApiApi.PATH_CREATE_NEW_USER,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> createNewUser(
        @Parameter(name = "User", description = "info regarding create User endpoint ", required = true) @Valid @RequestBody User user
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_EXCHANGE_TOKEN = "/api/v1/oauth2/token";
    /**
     * POST /api/v1/oauth2/token : exchange access_code
     * exhange access_code for accessToken and refreshToken
     *
     * @param createTokenRequest  (required)
     * @return exchange token response (status code 200)
     *         or bad request (status code 400)
     */
    @Operation(
        operationId = "exchangeToken",
        summary = "exchange access_code",
        description = "exhange access_code for accessToken and refreshToken",
        tags = { "client api" },
        responses = {
            @ApiResponse(responseCode = "200", description = "exchange token response", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CreateTokenResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "bad request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CreateTokenBadRequest.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ApiApi.PATH_EXCHANGE_TOKEN,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<CreateTokenResponse> exchangeToken(
        @Parameter(name = "CreateTokenRequest", description = "", required = true) @Valid @RequestBody CreateTokenRequest createTokenRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"accessToken\" : \"accessToken\", \"refreshToken\" : \"refreshToken\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GENERATE_REFRESH_TOKEN = "/api/v1/oauth2/refresh";
    /**
     * POST /api/v1/oauth2/refresh : generate accessToken and refreshToken
     *
     * @param refreshTokenRequest  (optional)
     * @return response to get value (status code 200)
     */
    @Operation(
        operationId = "generateRefreshToken",
        summary = "generate accessToken and refreshToken",
        tags = { "client api" },
        responses = {
            @ApiResponse(responseCode = "200", description = "response to get value", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = RefreshTokenResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ApiApi.PATH_GENERATE_REFRESH_TOKEN,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<RefreshTokenResponse> generateRefreshToken(
        @Parameter(name = "RefreshTokenRequest", description = "") @Valid @RequestBody(required = false) @Nullable RefreshTokenRequest refreshTokenRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"refreshToken\" : \"refreshToken\", \"accessToken\" : \"accessToken\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GITHUB_CALLBACK = "/api/oauth2/github/callback";
    /**
     * GET /api/oauth2/github/callback : callback with code and state
     * callback send by github id provider
     *
     * @param code  (required)
     * @param state  (required)
     * @return found response send by github oauth2 (status code 302)
     *         or Validation Error (status code 400)
     */
    @Operation(
        operationId = "githubCallback",
        summary = "callback with code and state",
        description = "callback send by github id provider",
        tags = { "outh2 callback" },
        responses = {
            @ApiResponse(responseCode = "302", description = "found response send by github oauth2"),
            @ApiResponse(responseCode = "400", description = "Validation Error")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ApiApi.PATH_GITHUB_CALLBACK
    )
    default ResponseEntity<Void> githubCallback(
        @NotNull @Parameter(name = "code", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "code", required = true) String code,
        @NotNull @Parameter(name = "state", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "state", required = true) String state
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GOOGLE_CALLBACK = "/api/oauth2/google/callback";
    /**
     * GET /api/oauth2/google/callback : callback with code and state
     * callback send by google id provider
     *
     * @param code  (required)
     * @param state  (required)
     * @return found response send by google oauth2 (status code 302)
     *         or Vaidation Error (status code 400)
     */
    @Operation(
        operationId = "googleCallback",
        summary = "callback with code and state",
        description = "callback send by google id provider",
        tags = { "outh2 callback" },
        responses = {
            @ApiResponse(responseCode = "302", description = "found response send by google oauth2"),
            @ApiResponse(responseCode = "400", description = "Vaidation Error")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ApiApi.PATH_GOOGLE_CALLBACK
    )
    default ResponseEntity<Void> googleCallback(
        @NotNull @Parameter(name = "code", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "code", required = true) String code,
        @NotNull @Parameter(name = "state", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "state", required = true) String state
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_LOGIN_USER = "/api/v1/login";
    /**
     * POST /api/v1/login : allow user to login to the system
     * client login
     *
     * @return login successful (status code 200)
     *         or bad request (status code 400)
     */
    @Operation(
        operationId = "loginUser",
        summary = "allow user to login to the system",
        description = "client login",
        tags = { "client api" },
        responses = {
            @ApiResponse(responseCode = "200", description = "login successful", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = LoginResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "bad request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = LoginValidationError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ApiApi.PATH_LOGIN_USER,
        produces = { "application/json" },
        consumes = { "application/x-www-form-urlencoded" }
    )
    default ResponseEntity<LoginResponse> loginUser(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"accessCode\" : \"accessCode\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_LOGOUT_USER = "/api/v1/logout";
    /**
     * DELETE /api/v1/logout : revoke user refresh token and session
     * client logout
     *
     * @param SESSION_  (required)
     * @return Logout user by expiring session and refreshToken (status code 204)
     */
    @Operation(
        operationId = "logoutUser",
        summary = "revoke user refresh token and session",
        description = "client logout",
        tags = { "client api" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Logout user by expiring session and refreshToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = ApiApi.PATH_LOGOUT_USER
    )
    default ResponseEntity<Void> logoutUser(
        @NotNull @Parameter(name = "SESSION_", description = "", required = true, in = ParameterIn.COOKIE) @CookieValue(name = "SESSION_") String SESSION_
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
